import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pluginsSidebar: [
    'inicio',
    {type: 'autogenerated', dirName: 'velevators'},
    {type: 'autogenerated', dirName: 'vcombat'},
    {type: 'autogenerated', dirName: 'vlottery'},
    {type: 'autogenerated', dirName: 'vstaff'},
    'recursos',
  ],
};

export default sidebars;

